version: '3'
services:
    nginx:
        ports:
        -   8080:80
    mariadb:
        ports:
        -   8306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb
        ports:
        -   8081:80
        environment:
            - 'PMA_HOST=mariadb'